import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/fonts.toml"
]

[env]
    TERM = "xterm-256color"

[window]
    decorations = "full"
    dynamic_title = false
    opacity = 0.65

    [window.dimensions]
        columns = 80
        lines = 24

    [window.padding]
        x = 0
        y = 0

[scrolling]
    history = 5_000
    multiplier = 3

#[[keyboard.bindings]]
#    key = "o"
#    mods = "Control"
#    [keyboard.bindings.command]
#    program = ""
#    args = [ ]
